# Generated by Django 3.1 on 2020-08-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20200809_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='categorie',
            field=models.ManyToManyField(blank=True, to='timeline.Categorie'),
        ),
    ]
