# Generated by Django 3.1 on 2020-08-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20200813_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='flashback_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de récit du flashback'),
        ),
    ]
