# Generated by Django 3.1 on 2020-08-18 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_evenement_flashback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnage',
            name='date_naissance',
            field=models.DateField(default=datetime.datetime(2020, 8, 18, 9, 1, 50, 947134)),
        ),
    ]
